### ISSUE TITLE
Can't set schema

### ISSUE THREAD

**Issue by almartel** [OHDSI/InspectOMOP#2]
Hi, This is likely a very dumb question but I've pip installed InspectOMOP v0.2.2 and tried to create an inspector:
```
inspector = iomop.Inspector(db_name)
inspector.get_schema_names()
```

> AttributeError: 'Inspector' object has no attribute 'get_schema_names'

Same result when insert a inspector.connect() command

Using SQLAcadamy directly works: 
```
test = create_engine(db_name)
itest = inspect(test)
itest.get_schema_names()
```

> Gives expected output: ['cdm', 'information_schema', 'public', 'results', 'temp']

-----------------------------------------------------------------------------------------------
Since the schema isn't defined, nothing else works. Am I missing something here?
Thanks!

**Comment by jbadger3** [comment]
Happy to help if I can.  The inspector from InspectOMOP is not the same object returned by `inspect` from SQLAlchemy, which is why you don't see the `get_schema_names` function.  Not sure about the result you are getting with connect().  To see if things are working I would do:
```python
inspector = iomop.Inspector(db_name)
print(inspector.tables)
```
to see if you are getting an appropriate connection to your database.  Let me know if that clears things up or if there is something else to address.

**Comment by almartel** [comment]
I've found my issue. I need to append "?options=-csearch_path%3Dschema_name" to my connection_url so inspector knows which of the available schema to use.
